Intercept the completion script inside bal shell script

diff --git a/resources/scripts/install b/resources/scripts/install
--- a/resources/scripts/install
+++ b/resources/scripts/install
@@ -43,6 +43,17 @@ if [ $? -ne '0' ]; then
   exit $?
 fi
 
+\cp $CURRENT_PATH/ballerina-command-@version@/scripts/bal_completion.bash $CURRENT_PATH/../scripts
+
+if [ $? -ne '0' ]; then
+  echo "error occurred while copying completion script file."
+  # remove already copied jar.
+  if [ -f "$CURRENT_PATH/../lib/ballerina-command-@version@.jar" ]; then
+        rm -rf $CURRENT_PATH/../lib/ballerina-command-@version@.jar
+  fi
+  exit $?
+fi
+
 echo "Updating environment variables"
 if [ -f "/usr/lib/ballerina/bin/ballerina" ] 
 then
